server:
  port: 9400
  ssl:
    key-store: classpath:springboot.p12
    key-store-password: password
    key-store-type: pkcs12
    key-alias: springboot
    key-password: password

spring:
  flyway:
    enabled: false
    accounts:
      enabled: true
      clean-disabled: true
      locations: classpath:com/hrrm/famoney/accounts/migration
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: welcome1
    driverClassName: org.postgresql.Driver