server:
  port: 9400
  http2.enabled: true

  ssl:
    key-store: classpath:springboot.p12
    key-store-password: password
    key-store-type: pkcs12
    key-alias: springboot
    key-password: password

spring:
  flyway:
    enabled: false
  jpa.show-sql: true

  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: welcome1
    driverClassName: org.postgresql.Driver
    hikari:
      schema: famoney
