/**
 * Accounts
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { EntryDataDto } from './entry-data.dto';
import { RefundDataDto } from './refund-data.dto';
import { TransferDataDto } from './transfer-data.dto';


export type MovementDataDto = EntryDataDto | RefundDataDto | TransferDataDto;

